#!/bin/bash
# ============================================================
# Offline REINFORCE++ Training Script (TD-advantage version)
#
# Changes vs. the original lora.sh you were running:
#   1. Dataset:      msswift_ppo_td.jsonl (preprocessed with TD advantage)
#                    generated by scripts_lexie/preprocess_td_advantage.py
#   2. Advantage:    use pre-computed td_advantage column directly
#                    (skip buggy group-mean baseline). This relies on the new
#                    --offline_reinforce_advantage_key arg.
#   3. KL estimator: switch K1 -> K3 (GRPO style). K1 had a sign issue
#                    that made zero-advantage samples act like "anti-SFT".
#                    This relies on the new --offline_reinforce_kl_estimator arg.
#   4. KL coef:      0.05 -> 0.01. K3 is well-behaved so we can keep a small
#                    anchor to base model without the previous destabilisation.
#   5. LR:           3e-6 -> 1e-6. Full FT of 8B with only ~50 effective
#                    steps is fragile; smaller LR is safer.
#   6. Whitening:    true -> false. With per_device_batch_size=1 whitening was
#                    already no-op; make it explicit to avoid confusion.
#   7. Epochs:       1 -> 2. Dataset is now 1737 rows; 2 epochs ≈ 54 steps.
#   8. Save:         epoch -> steps, every 20 steps, keep 5. Easier to
#                    inspect degenerate behaviours early.
# Usage:
#   1. Make sure preprocessing has produced msswift_ppo_td.jsonl, e.g.:
#        python3 scripts_lexie/preprocess_td_advantage.py \
#          --input  v5_thinking_export/msswift_ppo.jsonl \
#          --output v5_thinking_export/msswift_ppo_td.jsonl \
#          --min_abs_advantage 0.05 --drop_dead 1 --drop_trivial 1
#   2. bash examples/train/rlhf/offline_reinforce/lora_td.sh
# ============================================================

# ======================== 按需修改区 ========================

# 模型
MODEL="/mnt/gpfs/xuexiangyuan/model/qwen3-vl-8b-thinking"

# 预处理后数据集（注意：先跑 preprocess_td_advantage.py 生成）
DATASET="/mnt/gpfs/xuexiangyuan/workspace/mas_orchestra/mcts_data/v5_thinking_export/msswift_ppo_td.jsonl"

# 输出目录
OUTPUT_DIR="output/offline_reinforce_v5_td"

# GPU 设置
CUDA_VISIBLE_DEVICES="0,1"
NPROC_PER_NODE=2

# 训练模式: "lora" 或 "full"
TUNER_TYPE="full"

# 训练超参
NUM_EPOCHS=2
LEARNING_RATE=1e-6
BATCH_SIZE=1
GRAD_ACCUM=32
MAX_LENGTH=36864

# LoRA 参数（仅 TUNER_TYPE=lora 时生效）
LORA_RANK=8
LORA_ALPHA=32

# 离线 REINFORCE++ 专有
# KL penalty: with K3 estimator a small non-zero coef stabilizes the policy
KL_COEF=0.01
KL_ESTIMATOR="k3"            # "k1"(原始/不稳) 或 "k3"(GRPO-style，推荐)
WHITEN_ADVANTAGES=false      # batch=1 下本来就不生效，显式关掉
USE_RANK_ADVANTAGE=false

# === 直接用预计算的 TD advantage（关键改动） ===
ADVANTAGE_KEY="td_advantage"

# 下面这两个只是用于 logging（reward_mean 展示），trainer 会忽略它们来算 advantage
REWARD_KEY="reward"
ANSWER_KEY="answer"
REWARD_KEYS="expected_acc_reward"
REWARD_WEIGHTS="1"

# 保存 & 日志
SAVE_STRATEGY="steps"
SAVE_STEPS=20
SAVE_TOTAL_LIMIT=5
LOGGING_STEPS=5
EVAL_RATIO=0.01

# 日志平台
REPORT_TO="wandb"
export WANDB_PROJECT="${WANDB_PROJECT:-offline-reinforce-v5}"
export WANDB_RUN_NAME="${WANDB_RUN_NAME:-td_adv_k3kl}"
export WANDB_MODE="${WANDB_MODE:-offline}"

# ======================== 构建命令 ========================

ARGS=(
    --rlhf_type offline_reinforce
    --model "${MODEL}"
    --dataset "${DATASET}"
    --output_dir "${OUTPUT_DIR}"
    --tuner_type "${TUNER_TYPE}"
    --torch_dtype bfloat16
    --num_train_epochs ${NUM_EPOCHS}
    --per_device_train_batch_size ${BATCH_SIZE}
    --per_device_eval_batch_size ${BATCH_SIZE}
    --learning_rate ${LEARNING_RATE}
    --lr_scheduler_type cosine
    --gradient_accumulation_steps ${GRAD_ACCUM}
    --gradient_checkpointing true
    --max_length ${MAX_LENGTH}
    --warmup_ratio 0.05
    --weight_decay 0.1
    --save_strategy ${SAVE_STRATEGY}
    --save_steps ${SAVE_STEPS}
    --save_total_limit ${SAVE_TOTAL_LIMIT}
    --save_only_model true
    --logging_steps ${LOGGING_STEPS}
    --split_dataset_ratio ${EVAL_RATIO}
    --eval_strategy ${SAVE_STRATEGY}
    --eval_steps ${SAVE_STEPS}
    --dataloader_num_workers 4
    --offline_reinforce_kl_coef ${KL_COEF}
    --offline_reinforce_kl_estimator ${KL_ESTIMATOR}
    --offline_reinforce_whiten_advantages ${WHITEN_ADVANTAGES}
    --offline_reinforce_use_rank_advantage ${USE_RANK_ADVANTAGE}
    --offline_reinforce_reward_key "${REWARD_KEY}"
    --offline_reinforce_answer_key "${ANSWER_KEY}"
    --offline_reinforce_advantage_key "${ADVANTAGE_KEY}"
    --report_to ${REPORT_TO}
    --deepspeed zero2
)

if [ -n "${REWARD_KEYS:-}" ]; then
    ARGS+=(--offline_reinforce_reward_keys ${REWARD_KEYS})
fi
if [ -n "${REWARD_WEIGHTS:-}" ]; then
    ARGS+=(--offline_reinforce_reward_weights ${REWARD_WEIGHTS})
fi

# LoRA 模式追加参数
if [ "${TUNER_TYPE}" = "lora" ]; then
    ARGS+=(
        --lora_rank ${LORA_RANK}
        --lora_alpha ${LORA_ALPHA}
        --target_modules all-linear
    )
fi

# ======================== 启动训练 ========================

CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} \
NPROC_PER_NODE=${NPROC_PER_NODE} \
swift rlhf "${ARGS[@]}"
